Add the API implementation for the relationship widget (#33).
MusicConnectionMachine/api pull request #100
Opened 2017-04-18 01:51 UTC by chaoran-chen

Addressing #33, I've implemented a part of the API for the relationship widget.

@lustoykov, @martomi: Please take a look and tell me if it fits your requirements. I've chosen some other names than those in #33 because it seems to me that names like `subject` are more common used through our project than `primaryEntity`. But of course, I can change it. Just tell me every wish you have :)

@MusicConnectionMachine/group-3, @MusicConnectionMachine/group-4: I have no idea how to map an artist / work to a subject. Can you take care of it? ([Cf., code.](https://github.com/MusicConnectionMachine/api/compare/feature/api-for-relationship-widget?expand=1#diff-f3324d286d2ffee1c4b726eb65bdc3dcR8))

And what's about the autosuggestion? How should it be implemented? ([Cf., code.](https://github.com/MusicConnectionMachine/api/compare/feature/api-for-relationship-widget?expand=1#diff-f3324d286d2ffee1c4b726eb65bdc3dcR47))

2017-04-18 14:48 UTC, pfent commented on api/dsap/relationships.js
> +            // TODO Perform an actual search (Using Elasticsearch? PostgreSQL?)
This should probably be a postgres full-text search

2017-04-18 18:58 UTC, Henni commented on api/dsap/relationships.js
> +            // TODO Perform an actual search (Using Elasticsearch? PostgreSQL?)
@pfent :+1: , do you have any experience with this (and maybe even on how to do this in sequelize in a not completely ugly way)? I already experimented with some `ts_query` stuff and found a few helpful pages, but wasn't able to build anything useful with the sequelize syntax.

2017-04-18 19:13 UTC, Henni requested changes

2017-04-18 19:13 UTC, Henni commented on api/controllers/relationships.js
> +    var object = params.object ? params.object.value : undefined;
You can directly use `params.object.value` which evaluates to `undefined` if not given as parameter.

2017-04-18 19:14 UTC, Henni commented on api/dsap/relationships.js
> +            // TODO Map work to subject.
I'm looking into this.

2017-04-18 19:32 UTC, chaoran-chen commented on api/controllers/relationships.js
> +    var object = params.object ? params.object.value : undefined;
Ah, cool. Thanks!

2017-04-18 21:03 UTC, pfent commented on api/dsap/relationships.js
> +            // TODO Perform an actual search (Using Elasticsearch? PostgreSQL?)
@Henni Maybe for starters, you can use [pg_trgm](https://www.postgresql.org/docs/current/static/pgtrgm.html) to get suggestions for words. Just `sequelize.fn` the `similarity`, and get the top 5…

I'm not really sure, how well `ts_query` can map to sequelize…

2017-04-19 20:17 UTC, Henni commented on api/dsap/relationships.js
> +            // TODO Map work to subject.
Something like this should work:
```javascript
models.artists.findById(artistId)
  .then(artist => {
    return artist.getEntity();
  })
  .then(entity => {
    return entity.getRelEntity();
  });
```
This is pretty ugly as it creates three queries.

There should also be another way, like this:
```javascript
relEntities.findOne({
                attributes: ['id'],
                include: [{
                    model: entities,
                    include: [{
                        model: models.artists
                    }]
                }],
                where: {
                    '$artists.id$': artistId
                }
            })
```

This already includes some sequelize magic with the `$...$` which allows one to build a where clause on an included table, which is documented nowhere except for some Github issue. But it doesn't work and the query grows pretty large.

Maybe some Sequelize magician can jump in and fix this abomination of query...

2017-04-19 20:24 UTC, chaoran-chen commented on api/dsap/relationships.js
> +            // TODO Map work to subject.
You can just commit it if it works :)

2017-04-21 15:40 UTC, Henni approved these changes

2017-04-21 15:41 UTC, Henni commented
I added the mapper functions which *should* work. I wasn't really able to test it, as my local database currently is somehow broken...

2017-04-21 15:45 UTC, chaoran-chen commented
Thanks @Henni! Can someone, who actual has some real data, test it, please?

2017-04-21 16:32 UTC, pfent commented
@MusicConnectionMachine/group-3 @MusicConnectionMachine/group-4 do you have some data to test this?

2017-04-23 14:08 UTC, merged