Create the db schema with Sequelize
MusicConnectionMachine/api pull request #11
Opened 2017-03-16 15:58 UTC by TimHenkelmann

The "create_sequelize_schema.js" file will populate the database defined in the config.js file with the following entities:
- artist
- release
- recording
- work
- group
- instrument

2017-03-16 16:08 UTC, lgfrbcsgo commented
Great! @ShilpaGhanashyamGore also mentioned a table with all entities? We also need 2 additional tables. One to store website metadata and one to store mappings from entities to websites. See `Desired Table Structure` in Google Docs.

2017-03-16 16:10 UTC, lgfrbcsgo commented
The sequelize code should ideally be in the `api/helpers` folder

2017-03-16 18:08 UTC, TimHenkelmann commented
Alright, then I'll move them there and create a separate sequelize file for your tables!

2017-03-16 18:22 UTC, kordianbruck requested changes

2017-03-16 18:22 UTC, kordianbruck commented on api/helpers/create_sequelize_schema/config.js
> + */
Please remove those kinds of comments.

2017-03-16 18:22 UTC, kordianbruck commented on api/helpers/create_sequelize_schema/config.js
> +config.password = "1234";
Please make this file `json` so that you don't need to add exports and no one will ever dream of adding logic here.

2017-03-16 18:22 UTC, kordianbruck commented on api/helpers/create_sequelize_schema/create_sequelize_schema.js
> + */
again.

2017-03-16 18:22 UTC, kordianbruck commented on api/helpers/create_sequelize_schema/package.json
> +    "sequelize": "^3.30.2"
Please lock down the versions (remove ~ or ^) or use yarn (https://yarnpkg.com)

2017-03-16 18:38 UTC, TimHenkelmann commented on api/helpers/create_sequelize_schema/config.js
> + */
Whoops, sorry!

2017-03-16 18:40 UTC, TimHenkelmann commented
@kordianbruck applied your changes!

2017-03-16 19:14 UTC, kordianbruck approved these changes

2017-03-16 22:12 UTC, lgfrbcsgo commented
@TimHenkelmann would it also be possible to add the two tables requested in #10  so we have a way to store our metadata? According to @ShilpaGhanashyamGore you already have a table with all entities?

2017-03-17 08:55 UTC, sacdallago commented
I like this!

2017-03-17 09:04 UTC, sacdallago requested changes
I like this! But be aware that you will need the [Sequelize _classes_](https://github.com/MusicConnectionMachine/api/pull/11/files#diff-a0babe3ac085379280c3175db75ca2b9R24) throughout the API in order to make full use of the ORM idea.

Also. Please be a bit more reusable.

What you can do is the following:
1. Create a folder [here](https://github.com/MusicConnectionMachine/api/tree/develop/api) called `models`
2. For every model in [this](https://github.com/MusicConnectionMachine/api/pull/11/files#diff-a0babe3ac085379280c3175db75ca2b9R1) file, create a separate file, construct the table and export the class (e.g.`artist` --> `artist.js` --> `module.exports = new Sequelize.define('artists')`, `release`, ...).
3. Import and use the definitions where they are needed (E.g. In the controllers).
4. Import all definitions on bootstrap (eg. somwhere [here](https://github.com/MusicConnectionMachine/api/blob/develop/app.js#L11 ) and `sync` the tables).

2017-03-17 11:07 UTC, sacdallago commented
[UPDATE]
@TimHenkelmann I've added you to a private repo of mine, if you navigate to `app/models` you see what I mean. Also interesting are [this](https://github.com/sacdallago/mecu/tree/master/app/models) and [this](https://github.com/sacdallago/mecu/blob/master/app.js#L58)

💃

2017-03-17 13:49 UTC, TimHenkelmann commented
@lgfrbcsgo sorry for the late reply. Yes, I will also add those tables requested in #10. But as stated in #9 , the "entities" table is dropped.

2017-03-17 14:57 UTC, TimHenkelmann commented
@lgfrbcsgo I just saw that you will need the "entities" table for the "contains" table as a foreign key as stated in #10 , therefore we cannot remove it. Damn :D 
So my suggestions would be to create an "entities" table which will have the columns:
entity_id, type, type_id
where type can be "artist", "work", "release" or "instrument" and type_id will have the id in the respective table. This will allow us to reference all entities from one table without the issue of handling duplicate data (once in the entity table, once in the artist/work/release/instrument table). 
If you approve that, I will add this table to the Sequelize scripts

2017-03-17 17:36 UTC, TimHenkelmann commented
Currently it fails with the error: "Unhandled rejection SequelizeConnectionError: password authentication failed for user "musicmachine" => needs research

2017-03-17 17:41 UTC, lgfrbcsgo commented
@TimHenkelmann sound great!

2017-03-17 17:48 UTC, lgfrbcsgo commented
@TimHenkelmann sound great! Or you could add an extra column to all other tables containing a foreign key to entities. That way everything stays coherent when deleting stuff.

```
Entities(
    id:         int, primary key,
    type:       varchar
)

Artists(
    id:         int, primary key,
            ...
    entityId:   int, foreign key -> entities
)
```

2017-03-17 18:36 UTC, lgfrbcsgo commented
You have to use the keyword `on delete cascade` though

2017-03-19 11:49 UTC, kordianbruck commented
@sacdallago can you update your review please?

2017-03-19 15:02 UTC, TimHenkelmann commented
Fixed some issues and renamed table names to plural. Ready for review!

2017-03-19 15:05 UTC, ShilpaGhanashyamGore approved these changes
Looks good!

2017-03-19 15:41 UTC, TimHenkelmann commented
@sacdallago I just moved all the definitions and sequelize.sync into app.js and moved the models folder to /api. Could you please review it and delete your change request if everything looks good?

2017-03-19 16:29 UTC, merged

2017-03-19 16:30 UTC, kordianbruck commented
@TimHenkelmann he seems not to be around. I've merged it for you - looks good. Chris can still add his remarks and you'll just add a new PR then.